# Generated by Django 3.0 on 2022-12-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entradas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCriação', models.DateField()),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(max_length=250)),
                ('setor', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Saidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCriação', models.DateField()),
                ('dataPagamento', models.DateField()),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(max_length=250)),
                ('setor', models.CharField(max_length=150)),
            ],
        ),
    ]
